build: integral_serial pi_serial

integral_serial: integral_serial.cpp
	g++ -Wall integral_serial.cpp -o integral_serial

pi_serial: pi_serial.cpp
	g++ -Wall pi_serial.cpp -o pi_serial

clean:
	rm -f integral_serial pi_serial
